<?xml version="1.0" encoding="utf-8"?><Database Name="sample" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-BQF0PSQ\SQLEXPRESS;Initial Catalog=sample;Integrated Security=True" SettingsObjectName="LINQtoSQL.Properties.Settings" SettingsPropertyName="sampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.stud_table" Member="stud_tables">
    <Type Name="stud_table">
      <Column Name="rollno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dept" Member="depts">
    <Type Name="dept">
      <Column Name="deptnum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="dept_emp" Member="emps" ThisKey="deptnum" OtherKey="deptno" Type="emp" />
    </Type>
  </Table>
  <Table Name="dbo.emp" Member="emps">
    <Type Name="emp">
      <Column Name="eno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ename" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ph" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deptno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="desig" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="dept_emp" Member="dept" ThisKey="deptno" OtherKey="deptnum" Type="dept" IsForeignKey="true" />
    </Type>
  </Table>
</Database>